name: TorrServer
version: "1.3"
slug: torrserver
description: TorrServer media streaming server (custom add-on)
url: https://github.com/yourname/torrserver-hass
startup: services
boot: auto
arch:
  - amd64
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: "Web interface & API"
host_network: false
map:
  - config:rw
options:
  args: ""
schema:
  args: "str?"
