name: "TorrServer"
version: "1.7.17"
slug: "torrserver"
description: "TorrServer for Home Assistant"
arch:
  - aarch64 # Raspberry Pi 4, Odroid, 64-bit ARM
  - amd64 # Standard PCs/Servers, 64-bit x86
  - armhf # Raspberry Pi 2/3, 32-bit ARM hard float
  - armv7 # 32-bit ARM v7 devices
  - i386 # Legacy 32-bit x86 systems
startup: "application"
boot: "auto"
host_network: true
ports:
  8090/tcp: 8090
  443/tcp: 443
ports_description:
  8090/tcp: "Web Interface (HTTP)"
  443/tcp: "Web Interface (HTTPS)"
map:
  - share:rw
  - media:rw
  - ssl:ro
options:
  port: 8090
  path: "/data"
  ip: ""
  ssl: false
  sslport: 443
  torrentsdir: ""
  torrentaddr: ":49165"
  rdb: false
  httpauth: false
  dontkill: false
  ui: false
  maxsize: "0"
  sslcert: ""
  sslkey: ""
  logpath: ""
  weblogpath: ""
  pubipv4: ""
  pubipv6: ""
  searchwa: false
  tgtoken: ""
schema:
  port: int?
  path: str?
  ip: str?
  ssl: bool?
  sslport: int?
  torrentsdir: str?
  torrentaddr: str?
  rdb: bool?
  httpauth: bool?
  dontkill: bool?
  ui: bool?
  maxsize: str?
  sslcert: str?
  sslkey: str?
  logpath: str?
  weblogpath: str?
  pubipv4: str?
  pubipv6: str?
  searchwa: bool?
  tgtoken: str?
